import { Cal_Sans, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

import PromoBar from "../components/PromoBar/PromoBar";
import Header from "../components/Header/Header";
import NewsLetter from "../components/NewsLetter/NewsLetter";
import Footer from "../components/Footer/Footer";

const satoshi = Plus_Jakarta_Sans({
  variable: "--font-satoshi",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const integral = Cal_Sans({
  variable: "--font-integral",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${satoshi.variable} ${integral.variable}`}>
      <body>
        <PromoBar />
        <Header />

        {children}

        <NewsLetter />
        <Footer />
      </body>
    </html>
  );
}
